import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('/plane.gltf')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane005.geometry}
                material={materials['Material.020']}
                position={[0, -0.01, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle009.geometry}
                material={materials['Material.014']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle033.geometry}
                material={materials['Material.014']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube064.geometry}
                material={nodes.Cube064.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Icosphere.geometry}
                material={materials['Material.002']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle036.geometry}
                material={nodes.Circle036.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle037.geometry}
                material={materials.Material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle042.geometry}
                material={materials['Material.003']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube066.geometry}
                material={materials['Material.005']}
                position={[0, 0.055, 0]}
                scale={[1, 0.71, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath.geometry}
                material={nodes.NurbsPath.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath001.geometry}
                material={materials['Material.021']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube063.geometry}
                material={materials['Material.005']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube069.geometry}
                material={materials['Material.005']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube070.geometry}
                material={materials['Material.005']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube071.geometry}
                material={materials['Material.005']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Icosphere001.geometry}
                material={materials['Material.003']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane038.geometry}
                material={materials['Material.019']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube072.geometry}
                material={materials['Material.005']}
                position={[0, 0.06, 0]}
                scale={[1, 0.881, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube073.geometry}
                material={materials['Material.005']}
                position={[0, 0.035, 0]}
                scale={[1, 0.915, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane041.geometry}
                material={materials['Material.019']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube074.geometry}
                material={nodes.Cube074.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube075.geometry}
                material={nodes.Cube075.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube076.geometry}
                material={nodes.Cube076.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube077.geometry}
                material={nodes.Cube077.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube078.geometry}
                material={nodes.Cube078.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube079.geometry}
                material={nodes.Cube079.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane043.geometry}
                material={materials['Material.020']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane039.geometry}
                material={materials['Material.030']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane040.geometry}
                material={materials['Material.030']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube080.geometry}
                material={materials['Material.005']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane044.geometry}
                material={materials['Material.010']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle048.geometry}
                material={materials['Material.019']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle049.geometry}
                material={nodes.Circle049.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle050.geometry}
                material={materials.Material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle051.geometry}
                material={materials['Material.003']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle065.geometry}
                material={materials['Material.014']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle065_1.geometry}
                material={materials['Material.003']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle071.geometry}
                material={materials['Material.022']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle071_1.geometry}
                material={materials['Material.026']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane006.geometry}
                material={materials['Material.011']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane006_1.geometry}
                material={materials['Material.013']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle037_1.geometry}
                material={materials['Material.026']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle037_2.geometry}
                material={materials['Material.027']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_1.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere009_2.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere013.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere013_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere014.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere014_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere015.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere015_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere016.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere016_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere017.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere017_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere018.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere018_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere019.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere019_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere020.geometry}
                material={materials['Material.025']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere020_1.geometry}
                material={materials['Material.024']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle043.geometry}
                material={materials['Material.022']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle043_1.geometry}
                material={materials['Material.026']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle045_1.geometry}
                material={materials['Material.022']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle045_2.geometry}
                material={materials['Material.026']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle046_1.geometry}
                material={materials['Material.022']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle046_2.geometry}
                material={materials['Material.026']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle047_1.geometry}
                material={materials['Material.022']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle047_2.geometry}
                material={materials['Material.026']}
            />
        </group>
    )
}

useGLTF.preload('/plane.gltf')