import React from 'react'
import ProductsList from '../../components/wellness/ProductsList';
import TitleSection from '../../components/main/TitleSection';
import FooterAr from '@/app/components/main/FooterAr';
import HeaderAr from '@/app/components/main/HeaderAr';

export const metadata = {
  title: "Valeurs - Wellness Products",
  description: "Generated by Rockai Dev",
};



export default function page() {

  return (
    <>
      <HeaderAr translate={'/wellness'} />
      <TitleSection title={'حلولنا للصحة العامة'} />
      <section className="section min-h-screen w-full flex flex-col items-center justify-center">
        <ProductsList lang={'/ar'} />
      </section>
      
      <FooterAr />
    </>
  )
}
