import React from 'react'
import TitleSection from '../../components/main/TitleSection';
import FooterAr from '@/app/components/main/FooterAr';
import HeaderAr from '@/app/components/main/HeaderAr';

export const metadata = {
  title: "Valeurs - Medical Blogs",
  description: "Generated by Rockai Dev",
};


export default function page() {
  return (
    <>
      <HeaderAr translate={'/blogs'} />
      <TitleSection title={`مقالات عن الصحة العامة`} />
      <section className='min-h-screen'>

      </section>
      <FooterAr />
    </>
  )
}
