import React from 'react'
import TitleSection from '../../components/main/TitleSection';
import HeaderAr from '@/app/components/main/HeaderAr';
import FooterAr from '@/app/components/main/FooterAr';

export const metadata = {
  title: "Valeurs - Contact Us",
  description: "Generated by Rockai Dev",
};


export default function page() {
  return (
    <>
      <HeaderAr translate={'/contactus'} />
      <TitleSection title={`تواصل معنا`} />
      <section className='min-h-screen'>

      </section>
      <FooterAr />
    </>
  )
}
