import Header from "./components/main/Header";
import "./globals.css";


export const metadata = {
  title: "Valeurs Website",
  description: "Generated by Rockai Dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-mainColor flex items-center justify-center flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
