import DataProvider from "./components/Context/DataContext";
import "./globals.css";


export const metadata = {
  title: "Valeurs Website",
  description: "Generated by Rockai Dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-mainColor font-mainFont flex items-center justify-center flex-col" suppressHydrationWarning={true}>
        <DataProvider>
          {children}
        </DataProvider>
      </body>
    </html>
  );
}
