import React from 'react'
import TitleSection from '../components/main/TitleSection';
import Footer from '../components/main/Footer';
import Header from '../components/main/Header';
import HandleContactSend from '../components/contact/HandleContactSend';

export const metadata = {
  title: "Valeurs - Contact Us",
  description: "Generated by Rockai Dev",
};


export default function page() {
  return (
    <>
      <Header translate={'/ar/contactus'} />
      <TitleSection title={`Contact Valeurs`} />
      <section className=' mb-20 px-4'>
        <HandleContactSend />
      </section>
      <Footer />
    </>
  )
}
