import React from 'react'
import TitleSection from '../components/main/TitleSection';

export const metadata = {
  title: "Valeurs - Contact Us",
  description: "Generated by Rockai Dev",
};


export default function page() {
  return (
    <>
      <TitleSection title={`Contact Valeurs`} />
      <section className='min-h-screen'>

      </section>
      <Footer />
    </>
  )
}
