import React from 'react'
import TitleSection from '../components/main/TitleSection';
import Footer from '../components/main/Footer';

export const metadata = {
  title: "Valeurs - Medical Blogs",
  description: "Generated by Rockai Dev",
};


export default function page() {
  return (
    <>
      <TitleSection title={`Medical Blogs`} />
      <section className='min-h-screen'>

      </section>
      <Footer />
    </>
  )
}
