import React from 'react'
import TitleSection from '../components/main/TitleSection';
import Footer from '../components/main/Footer';
import Header from '../components/main/Header';

export const metadata = {
  title: "Valeurs - Medical Blogs",
  description: "Generated by Rockai Dev",
};


export default function page() {
  return (
    <>
      <Header translate={'/ar/blogs'} />
      <TitleSection title={`Medical Blogs`} />
      <section className='min-h-screen'>

      </section>
      <Footer />
    </>
  )
}
