import React from 'react'
import BgOCompany from '../../public/bgOurCompany.jpg'
import Image from 'next/image';
import Footer from '../components/main/Footer';
export const metadata = {
  title: "Valeurs - Our Company",
  description: "Generated by Rockai Dev",
};


export default function Page() {
  return (
    <>
      <section id='ouroverview' className="section w-full lg:h-screen relative h-[50vh] px-4 flex flex-col items-center justify-center" style={{
        backgroundImage: `url(${BgOCompany.src})`,
        backgroundAttachment: 'fixed',
        backgroundPosition: "center",
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat'
      }}>
        <div className="content text-start z-10 container h-full py-4 lg:h-[50%] flex flex-col w-full items-center justify-end">
          <h1 className='text-lg lg:text-4xl font-bold lg:mb-4'>At Valeurs, we are more than a provider of cutting-edge medical devices, we are ambassadors of wellness.</h1>
          <p className='text-sm lg:text-2xl'>With a commitment to enhancing the quality of life, we leverage the latest AI technologies to bring innovative solutions that empower healthcare professionals and improve patient outcomes. </p>
        </div>

        <div className="absolute inset-0 bg-white bg-opacity-70 filter blur-sm"></div>
        <div className="ground-trans absolute -bottom-1 left-0 w-full h-[150px]"></div>
      </section>
      <section id='text' className="section text-center w-full relative p-4 flex flex-col items-center justify-center my-10">
        <h2 className='text-xl lg:text-3xl font-bold'>Our products and services are designed to support a healthier future</h2>
        <p className='text-xl font-semibold lg:text-2xl mb-4'>Ensuring that every individual experiences the best in medical care and wellness.</p>
        <p className='text-xl max-w-6xl'>Valeurs is at the forefront of transforming wellness through innovative medical technologies. As wellness ambassadors, we are dedicated to enhancing the quality of life by providing advanced solutions powered by the latest AI technologies. Our vision is to lead in the delivery of superior healthcare solutions that empower individuals and health-care	 professionals alike.</p>
      </section>
      <div id='meetourteam' className="section my-10 p-4 text-center flex flex-col items-center justify-center">
        <h1 className='text-center text-4xl font-bold mb-4'>Meet Our Team</h1>
        <p className='text-lg font-medium max-w-6xl'>Behind every innovative solution at Valeurs is a team of passionate professionals committed to excellence. Our diverse team brings together expertise in healthcare, technology, and wellness to create impactful solutions for a healthier future.</p>
        <div className="TeamList flex flex-wrap items-center justify-center my-5 p-4">

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-full absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Muhammed Essawy</h4>
              <h6 className='text-xl'>CEO</h6>
            </div>
          </div>

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-full absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Raouf</h4>
              <h6 className='text-xl'>CFO</h6>
            </div>
          </div>

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-full absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Muhammed Essam</h4>
              <h6 className='text-xl'>Marketing Manager</h6>
            </div>
          </div>

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-full absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Muhammed Essam</h4>
              <h6 className='text-xl'>Sales Manager</h6>
            </div>
          </div>


        </div>
      </div>
      <Footer />
    </>
  )
}
