import React from 'react'
import BgOCompany from '../../public/bgOurCompany.jpg'
import BgHome from '../../public/bgHome.jpg'
import Image from 'next/image';
import Footer from '../components/main/Footer';
import AnimatedNumber from '../components/main/AnimateNumber';


export const metadata = {
  title: "Valeurs - Our Company",
  description: "Generated by Rockai Dev",
};


export default function Page() {
  return (
    <>
      <section id='ouroverview' className="section w-[95%] rounded-tr-xl rounded-bl-xl h-[85vh] my-[80px] relative px-4 flex flex-col items-center justify-center overflow-hidden" style={{
        backgroundImage: `url(${BgHome.src})`,
        backgroundAttachment: 'fixed',
        backgroundPosition: "start",
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat'
      }}>
        <div className="front flex flex-col items-center justify-center w-full z-10">
          <Image src={'/logoWhite.png'} width={250} height={250} alt='Valuers Logo' />
          <h1 className="my-10 text-center px-4 text-4xl lg:text-6xl font-bold z-[5] text-mainColor">Smart Solutions for <span className="text-priColor">Lifelong</span> Wellness.</h1>

          <div className="counter flex items-center justify-around flex-wrap w-full">
            <div className="part flex flex-col items-center justify-center m-4">
              <h2 className="text-5xl text-mainColor font-bold">+<AnimatedNumber number={15} /></h2>
              <h3 className="text-3xl font-medium text-mainColor">Partnerships</h3>
            </div>
            <div className="part flex flex-col items-center justify-center m-4">
              <h2 className="text-5xl text-mainColor font-bold">+<AnimatedNumber number={20000} /></h2>
              <h3 className="text-3xl font-medium text-mainColor">Cured Patient</h3>
            </div>
            <div className="part flex flex-col items-center justify-center m-4">
              <h2 className="text-5xl text-mainColor font-bold">+<AnimatedNumber number={60} /></h2>
              <h3 className="text-3xl font-medium text-mainColor">Social Activity</h3>
            </div>
          </div>
        </div>

        <div className="absolute inset-0 bg-whiteColor bg-opacity-90 filter"></div>
      </section>

      <section id='text' className="section text-center w-full relative p-4 max-w-5xl flex flex-col items-center justify-center my-[80px]">
        <h2 className='text-xl lg:text-3xl font-bold'>At Valeurs, our mission is to lead the way in wellness by delivering innovative medical solutions that enhance the quality of life</h2>
        <p className='text-xl font-semibold lg:text-2xl mb-4'>Leveraging cutting-edge AI technologies</p>
        <p className='text-xl max-w-6xl'>we empower healthcare professionals to achieve better patient outcomes and support a healthier future for all. Our commitment is to provide top-tier products and services that ensure every individual has access to exceptional medical care and wellness opportunities.</p>
      </section>

      <section
        className="w-full h-[40vh] relative my-10 bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage: `url(${BgOCompany.src})`,
          backgroundAttachment: 'fixed',
          backgroundSize: "cover",
        }}
      >
        <div className="absolute inset-0 bg-white bg-opacity-70 filter blur-sm"></div>
        <h2 className='lg:text-6xl text-2xl w-full text-whiteColor absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-center font-black mb-6'>We are ambassadors of wellness</h2>

      </section>

      <section id='text' className="section text-center w-full relative p-4 max-w-5xl flex flex-col items-center justify-center my-[80px]">
        <h2 className='text-xl lg:text-5xl mb-10 font-bold'>Our Vision</h2>
        <p className='text-xl font-semibold lg:text-3xl mb-4'>Our vision at Valeurs is to revolutionize wellness by harnessing innovative medical technologies</p>
        <p className='text-xl max-w-6xl'>As leaders and ambassadors of wellness, we are committed to enhancing the quality of life with AI-driven solutions, empowering healthcare professionals and individuals alike to achieve excellence in healthcare.</p>
      </section>
      

      <h2 className='text-xl lg:text-5xl my-10 font-bold'>Our Presence</h2>
      <section id='ouroverview' className="section w-[95%] rounded-tr-xl rounded-bl-xl h-[50vh] mb-[80px] relative px-4 flex flex-col items-center justify-center overflow-hidden" style={{
        backgroundImage: `url(${BgHome.src})`,
        backgroundAttachment: 'fixed',
        backgroundPosition: "start",
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat'
      }}>
        


        <div className="absolute inset-0 bg-whiteColor bg-opacity-90 filter"></div>
      </section>

      <section id='meetourteam' className="section my-[80px] p-4 text-center flex flex-col items-center justify-center">
        <h1 className='text-center text-4xl font-bold mb-4'>Meet Our Team</h1>
        <p className='text-lg font-medium max-w-6xl'>Behind every innovative solution at Valeurs is a team of passionate professionals committed to excellence. Our diverse team brings together expertise in healthcare, technology, and wellness to create impactful solutions for a healthier future.</p>
        <div className="TeamList flex flex-wrap items-center justify-center my-5 p-4">

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-tr-xl rounded-bl-xl absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-tr-xl rounded-bl-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Muhammed Essawy</h4>
              <h6 className='text-xl'>CEO</h6>
            </div>
          </div>

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-tr-xl rounded-bl-xl absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-tr-xl rounded-bl-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Raouf</h4>
              <h6 className='text-xl'>CFO</h6>
            </div>
          </div>

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-tr-xl rounded-bl-xl absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-tr-xl rounded-bl-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Muhammed Essam</h4>
              <h6 className='text-xl'>Marketing Manager</h6>
            </div>
          </div>

          <div className="person1 relative w-[300px] h-[230px] flex flex-col items-center justify-end m-2">
            <div className="image w-[250] h-[250] rounded-tr-xl rounded-bl-xl absolute top-0 left-1/2 -translate-x-1/2 overflow-hidden ">
              <Image className='hover:scale-110 duration-700' src={'/person1.png'} width={300} height={300} alt='person Name' />
            </div>
            <div className="details hover:shadow-lg duration-700 border-2 border-whiteColor pt-20 p-2 rounded-tr-xl rounded-bl-xl flex flex-col items-center justify-center w-full">
              <h4 className='text-xl font-bold text-center'>Dr. Muhammed Essam</h4>
              <h6 className='text-xl'>Sales Manager</h6>
            </div>
          </div>


        </div>
      </section>
      <Footer />
    </>
  )
}
