import React from 'react'

export const metadata = {
  title: "Valeurs - Wellness Products",
  description: "Generated by Rockai Dev",
};



export default function Page() {

  return (
    <div className="section w-full flex flex-col items-center justify-center">
      <h2 className='text-3xl font-bold text-whiteColor my-16 w-full text-center'>Wellness</h2>
      <div className="list flex flex-wrap items-center justify-center w-full my-8">

      </div>
    </div>
  )
}
