import React from 'react'
import ProductsList from '../components/wellness/ProductsList';
import Footer from '../components/main/Footer';

export const metadata = {
  title: "Valeurs - Wellness Products",
  description: "Generated by Rockai Dev",
};



export default function page() {

  return (
    <>
      <section className="section pt-20 min-h-screen w-full flex flex-col items-center justify-center">
        <h2 className='text-3xl font-bold text-whiteColor my-16 w-full text-center'>Wellness</h2>
        <ProductsList />
      </section>
      
      <Footer />
    </>
  )
}
